/**
 * OpenAPi Vinted
 * OpenApi documentation for Spring Security
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface OrderDto {
  id: number;
  date?: string;
  insertionIdList: Array<number>; // Provide a default empty array
  paymentMethod?: string;
  total?: number;
  userId: number;
}
