package com.example.vintedandroid.swagger.client.apis

import android.util.Log
import com.example.vintedandroid.model.LoggedUserDetails
import com.example.vintedandroid.swagger.client.infrastructure.RequestConfig

fun ConfigureAuthorizationBearer(localVariableConfig: RequestConfig): RequestConfig {
    Log.i("Bearer", "${LoggedUserDetails.getInstance().getCurrentUser().accessToken}")

    val headers = mutableMapOf<String, String>()
    // Add the Bearer token to the headers
    headers["Authorization"] = "Bearer ${LoggedUserDetails.getInstance().getCurrentUser().accessToken}"

    // Set the headers in the RequestConfig
    localVariableConfig.headers = headers
    return localVariableConfig
}

//val mutableHeaders = localVariableConfig.headers.toMutableMap()
//mutableHeaders["Authorization"] = "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJ1TkJYcVBTLUwtYlhxTUJPWEh5Nk1pZFBjQWdIU3FQeGtpQlpDa0hldWtVIn0.eyJleHAiOjE2OTM4MDcyMjMsImlhdCI6MTY5Mzc3MTIyMywianRpIjoiMjBkNjZkOWItZDI2NS00ZDRlLThhY2MtMjYzMDdhNDBhMzE3IiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDkwL3JlYWxtcy92aW50ZWQyXzAiLCJhdWQiOiJhY2NvdW50Iiwic3ViIjoiN2RhMDE3MzYtOTdkNi00YzIxLWE3MDEtMTMwYzk3YjNjNGFkIiwidHlwIjoiQmVhcmVyIiwiYXpwIjoidmludGVkLWNsaWVudCIsInNlc3Npb25fc3RhdGUiOiIwZjhiY2E3Yy04M2VmLTRjNzEtOWMzMC1mOTVmOGNiMTk3MzciLCJhY3IiOiIxIiwiYWxsb3dlZC1vcmlnaW5zIjpbImh0dHA6Ly9sb2NhbGhvc3Q6ODA5MSJdLCJyZWFsbV9hY2Nlc3MiOnsicm9sZXMiOlsiYXBwX3VzZXIiLCJvZmZsaW5lX2FjY2VzcyIsInVtYV9hdXRob3JpemF0aW9uIiwiZGVmYXVsdC1yb2xlcy12aW50ZWQyXzAiXX0sInJlc291cmNlX2FjY2VzcyI6eyJ2aW50ZWQtY2xpZW50Ijp7InJvbGVzIjpbInVzZXIiXX0sImFjY291bnQiOnsicm9sZXMiOlsibWFuYWdlLWFjY291bnQiLCJtYW5hZ2UtYWNjb3VudC1saW5rcyIsInZpZXctcHJvZmlsZSJdfX0sInNjb3BlIjoiZW1haWwgcHJvZmlsZSIsInNpZCI6IjBmOGJjYTdjLTgzZWYtNGM3MS05YzMwLWY5NWY4Y2IxOTczNyIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJzaGFkb3dzdG9ybSIsImVtYWlsIjoiam9obi5zbWl0aEBleGFtcGxlLmNvbSJ9.330WQQ72tYayNCG2Q3pN9aKxWdttEOA48ogE4tvghTb64Jsn58LuW9uWUsY1m09xzd-D4SL8KjE7q0gDhOI9HE7BMHW0DYz0YaSygjHH-bWhZF170kq3fKKnH_z-8OykWxlyYBk4ehkri_NB8yNG2aFgYj6OXC5jUV_0BgkZvEs6wBnz8FEdsMtYqQNctmAN83mS_5Df3NxcEMW2Nbz8Ez6w9AQlT0PNk5rDbgfmw0QA75A6kngu5JQw7nEboU3JINKRiS-pm1v46H1F2MG37kurJiy3ms03U22cfY-Dc46AO3_eLVXrSOh4NWOOw7a1aWCrUDsUzNRPzw5kZUjCiw"