spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8090/realms/vinted2_0
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
  server:
    port: 8091

jwt:
  auth:
    converter:
      resource-id: vinted-client
      principle-attribute: preferred_username

server:
  ssl:
    key-alias: spring-https
    key-store: classpath:javatechie.jks
    key-store-type: JKS
    key-password: vinted
    key-store-password: vinted

  port: 8010

resilience4j:
  circuitbreaker:
    instances:
      serviceA:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
  retry:
    instances:
      serviceA:
        registerHealthIndicator: true
        maxRetryAttempts: 5
        waitDuration: 10s
ratelimiter:
  instances:
    serviceA:
      registerHealthIndicator: true
      limitForPeriod: 3
      limitRefreshPeriod: 10s
      timeoutDuration: 3s
management:
  server:
    port: 8082
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always