/**
 * OpenAPi Vinted
 * OpenApi documentation for Spring Security
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface BasicInsertionDto {
    id: number;
    title: string;
    price: number;
    description?: string;
    condition?: string;
    creationDate: string;
    endDate?: string;
    imagePath?: string;
    userId: number;
    image: Blob;

}
