/**
 * OpenAPi Vinted
 * OpenApi documentation for Spring Security
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface BasicInsertionDto {
    id: number;
    title: string;
    price: number;
    description?: string;
    condition?: string;
    creationDate: string;
    category?: Category.CategoryEnum;
    brand?: Brand.BrandEnum;
    endDate?: string;
    imagePath?: string;
    userId: number;
    image: Blob;

}

export namespace Category {
  export type CategoryEnum =
    | 'DONNA'
    | 'UOMO'
    | 'COLLEZIONI'
    | 'ELETTRONICA'
    | 'SPORT'
    | 'ABBIGLIAMENTO'
    | 'BARCHE'
    | 'BAMBINI';

  export const CategoryEnum = {
    DONNA: 'DONNA' as CategoryEnum,
    UOMO: 'UOMO' as CategoryEnum,
    COLLEZIONI: 'COLLEZIONI' as CategoryEnum,
    ELETTRONICA: 'ELETTRONICA' as CategoryEnum,
    SPORT: 'SPORT' as CategoryEnum,
    ABBIGLIAMENTO: 'ABBIGLIAMENTO' as CategoryEnum,
    BARCHE: 'BARCHE' as CategoryEnum,
    BAMBINI: 'BAMBINI' as CategoryEnum,
  };
}

export namespace Brand {
  export type BrandEnum =
     'Adidas'
    | 'Puma'
    | 'Nike'
    | 'Microsoft'
    | 'Xiaomi'
    | 'Nothing'
    | 'Guess'
    | 'Pumpling'
    | 'Fila'
    | 'Onze'
    | 'Gojiang'
    | 'Rebook'
    | 'New_Balance'
    | 'Asix'
    | 'Sony';

  export const BrandEnum = {
    Adidas: 'Adidas' as BrandEnum,
    Puma: 'Puma' as BrandEnum,
    Nike: 'Nike' as BrandEnum,
    Microsoft: 'Microsoft' as BrandEnum,
    Xiaomi: 'Xiaomi' as BrandEnum,
    Nothing: 'Nothing' as BrandEnum,
    Guess: 'Guess' as BrandEnum,
    Pumpling: 'Pumpling' as BrandEnum,
    Fila: 'Fila' as BrandEnum,
    Onze: 'Onze' as BrandEnum,
    Gojiang: 'Gojiang' as BrandEnum,
    Rebook: 'Rebook' as BrandEnum,
    New_Balance: 'New_Balance' as BrandEnum,
    Asix: 'Asix' as BrandEnum,
    Sony: 'Sony' as BrandEnum
  };
}

