/**
 * OpenAPi Vinted
 * OpenApi documentation for Spring Security
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface OrderDto {
    id: number | null;
    date?: string;
    paymentId: number | null;
    insertionIdList?: Number[];
    total?: number;
    userId: number;
}
