/**
 * OpenAPi Vinted
 * OpenApi documentation for Spring Security
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import {BasicInsertion} from "./basicInsertion";
import {Order} from "./order";
import PaymentMethodEnum = Order.PaymentMethodEnum;

export interface OrderDto {
    id: number;
    date?: string;
    insertionIdList?: Array<BasicInsertion>;
    total?: number;
    userId: number;
    payment_method: string;
}
