/**
 * OpenAPi Vinted
 * OpenApi documentation for Spring Security
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface OrderDto {
    id: number;
    data: string
    number: number;
    creationDate: string;
    total: number;
    //paymentId: number;
    insertionId: number[];
    userId: number;
}
