/**
 * OpenAPi Vinted
 * OpenApi documentation for Spring Security
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Address } from './address';
import { BasicInsertion } from './basicInsertion';
import { BuyingOffer } from './buyingOffer';
import { Order } from './order';

export interface User { 
    id?: number;
    firstName?: string;
    lastName?: string;
    address?: Address;
    nickname?: string;
    email?: string;
    password?: string;
    role?: User.RoleEnum;
    phoneNumber?: number;
    registrationDate?: string;
    imageName?: string;
    isPrivate?: boolean;
    buyingOffers?: Array<BuyingOffer>;
    orders?: Array<Order>;
    insertions?: Array<BasicInsertion>;
    favorites?: Array<BasicInsertion>;
}
export namespace User {
    export type RoleEnum = 'ADMIN' | 'USER';
    export const RoleEnum = {
        ADMIN: 'ADMIN' as RoleEnum,
        USER: 'USER' as RoleEnum
    };
}