/**
 * OpenAPi Vinted
 * OpenApi documentation for Spring Security
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BasicInsertionDto } from './basicInsertionDto';

export interface V1InsertionsBody {
    insertion: BasicInsertionDto;
    img?: Blob;
}
