/**
 * OpenAPi Vinted
 * OpenApi documentation for Spring Security
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.example.vintedandroid.swagger.client.models


/**
 * 
 * @param street 
 * @param number 
 * @param city 
 * @param cap 
 * @param state 
 * @param region 
 */
data class Address (

    val street: kotlin.String? = null,
    val number: kotlin.String? = null,
    val city: kotlin.String? = null,
    val cap: kotlin.String? = null,
    val state: kotlin.String? = null,
    val region: kotlin.String? = null
) {
}