/**
 * OpenAPi Vinted
 * OpenApi documentation for Spring Security
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.example.vintedandroid.swagger.client.models

import java.io.Serializable


/**
 * 
 * @param id 
 * @param title 
 * @param price 
 * @param description 
 * @param creationDate 
 * @param isPrivate 
 * @param imageName 
 * @param brand 
 * @param category 
 * @param available 
 * @param userId 
 */
data class BasicInsertionDto (

    val id: kotlin.Long? = null,
    val title: kotlin.String,
    var price: kotlin.Float,
    val description: kotlin.String,
    val creationDate: Any? = null, //java.time.LocalDate
    val isPrivate: kotlin.Boolean? = null,
    val imageName: kotlin.String? = null,
    val brand: Brand? = null,
    val category: Category? = null,
    val available: kotlin.Boolean? = null,
    val userId: kotlin.Long
) {
    /**
    * 
    * Values: ADIDAS,PUMA,NIKE,MICROSOFT,XIAOMI,NOTHING,GUESS,PUMPLING,FILA,ONZE,GOJIANG,REBOOK,NEWBALANCE,ASIX,SONY,ALTRO
    */
    enum class Brand(val value: kotlin.String){
        Adidas("Adidas"),
        Puma("Puma"),
        Nike("Nike"),
        Microsoft("Microsoft"),
        Xiaomi("Xiaomi"),
        Nothing("Nothing"),
        Guess("Guess"),
        Pumpling("Pumpling"),
        Fila("Fila"),
        Onze("Onze"),
        Gojiang("Gojiang"),
        Rebook("Rebook"),
        Asix("Asix"),
        Sony("Sony"),
        ALTRO("ALTRO");
    }
    /**
    * 
    * Values: ELETTRONICA,COLLEZIONI,ABBIGLIAMENTO,BARCHE,SPORT,DONNA,UOMO,BAMBINI,ALTRO
    */
    enum class Category(val value: kotlin.String){
        ELETTRONICA("ELETTRONICA"),
        COLLEZIONI("COLLEZIONI"),
        ABBIGLIAMENTO("ABBIGLIAMENTO"),
        BARCHE("BARCHE"),
        SPORT("SPORT"),
        DONNA("DONNA"),
        UOMO("UOMO"),
        BAMBINI("BAMBINI"),
        ALTRO("ALTRO");
    }
}