/**
 * OpenAPi Vinted
 * OpenApi documentation for Spring Security
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.example.vintedandroid.swagger.client.models

/**
 * 
 * @param id 
 * @param title 
 * @param available 
 * @param price 
 * @param creationDate 
 * @param description 
 * @param imageName 
 * @param isPrivate 
 * @param category 
 * @param brand 
 * @param buyingOffers 
 * @param user 
 * @param order 
 */
data class BasicInsertion (

    val id: kotlin.Long? = null,
    val title: kotlin.String? = null,
    val available: kotlin.Boolean? = null,
    val price: kotlin.Float? = null,
    val creationDate: java.time.LocalDate? = null,
    val description: kotlin.String? = null,
    val imageName: kotlin.String? = null,
    val isPrivate: kotlin.Boolean? = null,
    val category: Category? = null,
    val brand: Brand? = null,
    val buyingOffers: kotlin.Array<BuyingOffer>? = null,
    val user: User? = null,
    val order: Order? = null
) {
    /**
    * 
    * Values: ELETTRONICA,COLLEZIONI,ABBIGLIAMENTO,BARCHE,SPORT,DONNA,UOMO,BAMBINI,ALTRO
    */
    enum class Category(val value: kotlin.String){
        ELETTRONICA("ELETTRONICA"),
        COLLEZIONI("COLLEZIONI"),
        ABBIGLIAMENTO("ABBIGLIAMENTO"),
        BARCHE("BARCHE"),
        SPORT("SPORT"),
        DONNA("DONNA"),
        UOMO("UOMO"),
        BAMBINI("BAMBINI"),
        ALTRO("ALTRO");
    }
    /**
    * 
    * Values: ADIDAS,PUMA,NIKE,MICROSOFT,XIAOMI,NOTHING,GUESS,PUMPLING,FILA,ONZE,GOJIANG,REBOOK,NEWBALANCE,ASIX,SONY,ALTRO
    */
    enum class Brand(val value: kotlin.String){
        ADIDAS("Adidas"),
        PUMA("Puma"),
        NIKE("Nike"),
        MICROSOFT("Microsoft"),
        XIAOMI("Xiaomi"),
        NOTHING("Nothing"),
        GUESS("Guess"),
        PUMPLING("Pumpling"),
        FILA("Fila"),
        ONZE("Onze"),
        GOJIANG("Gojiang"),
        REBOOK("Rebook"),
        NEWBALANCE("New_Balance"),
        ASIX("Asix"),
        SONY("Sony"),
        ALTRO("ALTRO");
    }
}