/**
 * OpenAPi Vinted
 * OpenApi documentation for Spring Security
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.example.vintedandroid.swagger.client.models

/**
 * 
 * @param id 
 * @param price 
 * @param status 
 * @param insertion 
 * @param user 
 */
data class BuyingOffer (

    val id: kotlin.Long? = null,
    val price: kotlin.Float? = null,
    val status: Status? = null,
    val insertion: BasicInsertion? = null,
    val user: User? = null
) {
    /**
    * 
    * Values: PENDING,APPROVED,REFUSED
    */
    enum class Status(val value: kotlin.String){
        PENDING("PENDING"),
        APPROVED("APPROVED"),
        REFUSED("REFUSED");
    }
}