/**
 * OpenAPi Vinted
 * OpenApi documentation for Spring Security
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.example.vintedandroid.swagger.client.models


/**
 * 
 * @param id 
 * @param price 
 * @param status 
 * @param insertionId 
 * @param userId 
 */
data class BuyingOfferDto (

    val id: kotlin.Long? = null,
    val price: kotlin.Float,
    var status: String? = null,
    val insertionId: kotlin.Long,
    val userId: kotlin.Long
) {
    /**
    * 
    * Values: PENDING,APPROVED,REFUSED
    */
    enum class Status(val value: kotlin.String){
        PENDING("\"PENDING\""),
        APPROVED("\"APPROVED\""),
        REFUSED("\"REFUSED\"");
    }
}