/**
 * OpenAPi Vinted
 * OpenApi documentation for Spring Security
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.example.vintedandroid.swagger.client.models


/**
 *
 * @param id
 * @param sender
 * @param reciver
 * @param nickname
 * @param message
 * @param date
 * @param seen
 * @param chat
 */
data class ChatMessage (

    val id: kotlin.Long? = null,
    val sender: kotlin.Long? = null,
    val reciver: kotlin.Long? = null,
    val nickname: kotlin.String? = null,
    val message: kotlin.String? = null,
    val date: java.time.LocalDateTime? = null,
    val seen: kotlin.Boolean? = null,
    val chat: kotlin.Long? = null
) {
}