package com.example.vintedandroid.swagger.client.models

/**
 * OpenAPi Vinted
 * OpenApi documentation for Spring Security
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



/**
 *
 * @param sender
 * @param reciver
 * @param message
 * @param insertionId
 * @param user1NameLastname
 * @param user2NameLastname
 * @param insertionTitle
 */
data class NewChatDto (

    val sender: kotlin.Long? = null,
    val reciver: kotlin.Long? = null,
    val message: kotlin.String? = null,
    val insertionId: kotlin.Long? = null,
    val user1NameLastname: kotlin.String? = null,
    val user2NameLastname: kotlin.String? = null,
    val insertionTitle: kotlin.String? = null
) {
}