/**
 * OpenAPi Vinted
 * OpenApi documentation for Spring Security
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.example.vintedandroid.swagger.client.models


/**
 * 
 * @param sender 
 * @param reciver 
 * @param message 
 * @param chatId 
 */
data class NewMessageDto (

    val sender: kotlin.Long? = null,
    val reciver: kotlin.Long? = null,
    val message: kotlin.String? = null,
    val chatId: kotlin.Long? = null
) {
}