/**
 * OpenAPi Vinted
 * OpenApi documentation for Spring Security
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.example.vintedandroid.swagger.client.models


/**
 * 
 * @param password 
 * @param nickname 
 * @param firstname 
 * @param email 
 * @param lastname 
 * @param addressStreet 
 * @param addressNumber 
 * @param addressCity 
 * @param addressCap 
 */
data class NewUserDto (

    val password: kotlin.String,
    val nickname: kotlin.String,
    val firstname: kotlin.String,
    val email: kotlin.String? = null,
    val lastname: kotlin.String? = null,
    val addressStreet: kotlin.String? = null,
    val addressNumber: kotlin.Int? = null,
    val addressCity: kotlin.String? = null,
    val addressCap: kotlin.Int? = null
) {
}