/**
 * OpenAPi Vinted
 * OpenApi documentation for Spring Security
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.example.vintedandroid.swagger.client.models


/**
 * 
 * @param id 
 * @param date 
 * @param paymentMethod 
 * @param insertionIdList 
 * @param total 
 * @param userId 
 */
data class OrderDto (

    val id: kotlin.Long,
    val date: kotlin.String? = null,
    val paymentMethod: kotlin.String? = null,
    val insertionIdList: kotlin.Array<kotlin.Long>? = null,
    val total: kotlin.Float? = null,
    val userId: kotlin.Long
) {
}