/**
 * OpenAPi Vinted
 * OpenApi documentation for Spring Security
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.example.vintedandroid.swagger.client.models

/**
 * 
 * @param id 
 * @param date 
 * @param total 
 * @param paymentMethod 
 * @param status 
 * @param user 
 * @param insertionList 
 */
data class Order (

    val id: kotlin.Long? = null,
    val date: java.time.LocalDate? = null,
    val total: kotlin.Float? = null,
    val paymentMethod: PaymentMethod? = null,
    val status: Status? = null,
    val user: User? = null,
    val insertionList: kotlin.Array<BasicInsertion>? = null
) {
    /**
    * 
    * Values: CARD,PAYPAL,MARK
    */
    enum class PaymentMethod(val value: kotlin.String){
        CARD("CARD"),
        PAYPAL("PAYPAL"),
        MARK("MARK");
    }
    /**
    * 
    * Values: PENDING,APPROVED,REFUSED
    */
    enum class Status(val value: kotlin.String){
        PENDING("PENDING"),
        APPROVED("APPROVED"),
        REFUSED("REFUSED");
    }
}