/**
 * OpenAPi Vinted
 * OpenApi documentation for Spring Security
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.example.vintedandroid.swagger.client.models

/**
 * 
 * @param totalPages 
 * @param totalElements 
 * @param pageable 
 * @param first 
 * @param last 
 * @param size 
 * @param content 
 * @param number 
 * @param sort 
 * @param numberOfElements 
 * @param empty 
 */
data class PageOrderDto (

    val totalPages: kotlin.Int? = null,
    val totalElements: kotlin.Long? = null,
    val pageable: PageableObject? = null,
    val first: kotlin.Boolean? = null,
    val last: kotlin.Boolean? = null,
    val size: kotlin.Int? = null,
    val content: kotlin.Array<OrderDto>? = null,
    val number: kotlin.Int? = null,
    val sort: SortObject? = null,
    val numberOfElements: kotlin.Int? = null,
    val empty: kotlin.Boolean? = null
) {
}