/**
 * OpenAPi Vinted
 * OpenApi documentation for Spring Security
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.example.vintedandroid.swagger.client.models


/**
 * 
 * @param timestamp 
 * @param url 
 * @param message 
 */
data class ServiceError (

    val timestamp: java.time.LocalDateTime? = null,
    val url: kotlin.String? = null,
    val message: kotlin.String? = null
) {
}