/**
 * OpenAPi Vinted
 * OpenApi documentation for Spring Security
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.example.vintedandroid.swagger.client.models


/**
 * 
 * @param sorted 
 * @param empty 
 * @param unsorted 
 */
data class SortObject (

    val sorted: kotlin.Boolean? = null,
    val empty: kotlin.Boolean? = null,
    val unsorted: kotlin.Boolean? = null
) {
}