/**
 * OpenAPi Vinted
 * OpenApi documentation for Spring Security
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.example.vintedandroid.swagger.client.models

import com.example.vintedandroid.swagger.client.models.BasicInsertionDto

/**
 * 
 * @param insertion 
 * @param img 
 */
data class V1InsertionsBody (

    val insertion: BasicInsertionDto,
    val img: kotlin.Array<kotlin.Byte>
) {
}