spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          #Collegamento con keycloak
          issuer-uri: http://localhost:8090/realms/vinted2_0
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
  server:
    port: 8091

jwt:
  auth:
    converter:
      resource-id: vinted-client
      principle-attribute: preferred_username

server:

  ssl:
    #Si occupa di mettere HTTPS
    key-alias: vinted
    key-store: classpath:keystore.jks #path dove risiede la chiave
    key-store-type: JKS
    key-password: vinted
    key-store-password: vinted

  #mette il server in ascolto sulla porta 8010
  port: 8010

  #Imposta la scritta dopo http://localhost:8010 PER TUTTO IL PROGETTO
  #In questo caso http://localhost:8010/vintedProject-api
  servlet:
    context-path: /vintedProject-api
  #Ricorda che se modifichi questo, DEVI modificare il server url nella classe OpenApiConfig per far si che swagger faccia le GET,POST,ecc ai giusti endpoint!

