/**
 * OpenAPi Vinted
 * OpenApi documentation for Spring Security
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.example.vintedandroid.client.models


/**
 * 
 * @param id 
 * @param title 
 * @param price 
 * @param description 
 * @param condition 
 * @param creationDate 
 * @param isPrivate 
 * @param endDate 
 * @param imageName 
 * @param brand 
 * @param category 
 * @param userId 
 */
data class BasicInsertionDto (

    val id: kotlin.Long,
    val title: kotlin.String,
    val price: kotlin.Float,
    val description: kotlin.String? = null,
    val condition: kotlin.String? = null,
    val creationDate: Any? = null,
    val isPrivate: kotlin.Boolean? = null,
    val endDate: Any? = null,
    val imageName: kotlin.String? = null,
    val brand: Brand? = null,
    val category: Category? = null,
    val userId: kotlin.Long
) {
    /**
    * 
    * Values: ADIDAS,PUMA,NIKE,MICROSOFT,XIAOMI,NOTHING,GUESS,PUMPLING,FILA,ONZE,GOJIANG,REBOOK,NEWBALANCE,ASIX,SONY
    */
    enum class Brand(val value: kotlin.String){
        ADIDAS("Adidas"),
        PUMA("Puma"),
        NIKE("Nike"),
        MICROSOFT("Microsoft"),
        XIAOMI("Xiaomi"),
        NOTHING("Nothing"),
        GUESS("Guess"),
        PUMPLING("Pumpling"),
        FILA("Fila"),
        ONZE("Onze"),
        GOJIANG("Gojiang"),
        REBOOK("Rebook"),
        NEWBALANCE("New_Balance"),
        ASIX("Asix"),
        SONY("Sony");
    }
    /**
    * 
    * Values: ELETTRONICA,COLLEZIONI,ABBIGLIAMENTO,BARCHE,SPORT,DONNA,UOMO,BAMBINI
    */
    enum class Category(val value: kotlin.String){
        ELETTRONICA("ELETTRONICA"),
        COLLEZIONI("COLLEZIONI"),
        ABBIGLIAMENTO("ABBIGLIAMENTO"),
        BARCHE("BARCHE"),
        SPORT("SPORT"),
        DONNA("DONNA"),
        UOMO("UOMO"),
        BAMBINI("BAMBINI");
    }
}