/**
 * OpenAPi Vinted
 * OpenApi documentation for Spring Security
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.example.vintedandroid.client.models


/**
 * 
 * @param id 
 * @param title 
 * @param price 
 * @param description 
 * @param condition 
 * @param creationDate 
 * @param endDate 
 * @param imagePath 
 * @param userId 
 */
data class BasicInsertionDto (

    val id: kotlin.Long,
    val title: kotlin.String,
    val price: kotlin.Float,
    val description: kotlin.String? = null,
    val condition: kotlin.String? = null,
    val creationDate: Any? = null,
    val endDate: Any? = null,
    val imagePath: kotlin.String? = null,
    val userId: kotlin.Long
) {
}