/**
 * OpenAPi Vinted
 * OpenApi documentation for Spring Security
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.example.vintedandroid.client.models


/**
 * 
 * @param password 
 * @param nickName 
 * @param email 
 */
data class NewUserDto (

    val password: kotlin.String,
    val nickName: kotlin.String,
    val email: kotlin.String? = null
) {
}