/**
 * OpenAPi Vinted
 * OpenApi documentation for Spring Security
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.example.vintedandroid.client.models


/**
 * 
 * @param id 
 * @param date 
 * @param number 
 * @param paymentId 
 * @param insertionId 
 * @param userId 
 */
data class OrderDto (

    val id: kotlin.Long,
    val date: java.time.LocalDate? = null,
    val number: kotlin.Int,
    val paymentId: kotlin.Long,
    val insertionId: kotlin.Long,
    val userId: kotlin.Long
) {
}