/**
 * OpenAPi Vinted
 * OpenApi documentation for Spring Security
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.example.vintedandroid.client.models

/**
 * 
 * @param offset 
 * @param sort 
 * @param pageNumber 
 * @param pageSize 
 * @param paged 
 * @param unpaged 
 */
data class PageableObject (

    val offset: kotlin.Long? = null,
    val sort: SortObject? = null,
    val pageNumber: kotlin.Int? = null,
    val pageSize: kotlin.Int? = null,
    val paged: kotlin.Boolean? = null,
    val unpaged: kotlin.Boolean? = null
) {
}