/**
 * OpenAPi Vinted
 * OpenApi documentation for Spring Security
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.example.vintedandroid.client.models


/**
 * 
 * @param id 
 * @param paymentMethod 
 * @param status 
 * @param userId 
 * @param orderId 
 */
data class PaymentDto (

    val id: kotlin.Long,
    val paymentMethod: PaymentMethod? = null,
    val status: Status? = null,
    val userId: kotlin.Long,
    val orderId: kotlin.Long
) {
    /**
    * 
    * Values: CARD,PAYPAL,MARK
    */
    enum class PaymentMethod(val value: kotlin.String){
        CARD("CARD"),
        PAYPAL("PAYPAL"),
        MARK("MARK");
    }
    /**
    * 
    * Values: PENDING,APPROVED
    */
    enum class Status(val value: kotlin.String){
        PENDING("PENDING"),
        APPROVED("APPROVED");
    }
}