spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8090/realms/vinted2_0
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
  server:
    port: 8091

jwt:
  auth:
    converter:
      resource-id: vinted-client
      principle-attribute: preferred_username

server:
  ssl:
    enable: true
    key-alias: local_ssl
    key-store: classpath:local-ssl.p12
    key-store-type: PKCS12
    key-password: vinted
    key-store-password: vinted

  port: 8010
